# Generated by Django 3.1.3 on 2021-02-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_code', '0002_auto_20210213_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geo_code',
            name='id',
        ),
        migrations.AlterField(
            model_name='geo_code',
            name='seo_id',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
